// filepath: /Users/rolle/git/elexive-calc/src/pdf/components/ReportContentPage.js
// Content page component for PDF report generation

import React from 'react';
import { Page, Text, View } from '@react-pdf/renderer';
import styles from '../utils/pdfStyles';
import { getColorFromCssVar } from '../utils/colors';

/**
 * The content page of the PDF report
 */
const ReportContentPage = ({ 
  totalPrice, 
  completionTimeWeeks, 
  totalEvcValue, 
  formatNumber, 
  modulesByPillar, 
  resourceAllocation
}) => {
  // Get primary color from utility function instead of hardcoding
  const elexivePrimary = getColorFromCssVar('--elexive-primary', '#2E2266');
  
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.contentPage}>
        <Text style={styles.sectionTitle}>Investment Summary</Text>
        
        {/* Price Summary */}
        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.summaryLabel}>Weekly Investment:</Text>
            <Text style={styles.summaryValue}>€{formatNumber(totalPrice)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.summaryLabel}>Estimated Completion:</Text>
            <Text style={styles.summaryValue}>{completionTimeWeeks} weeks</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.summaryLabel}>Total EVCs:</Text>
            <Text style={styles.summaryValue}>{totalEvcValue}</Text>
          </View>
        </View>
        
        {/* Module breakdown */}
        <Text style={styles.sectionTitle}>Selected Modules</Text>
        {Object.entries(modulesByPillar || {}).map(([pillar, modules], index) => (
          <View key={index} style={styles.section}>
            <Text style={styles.pillarTitle}>{pillar}</Text>
            {modules.map((module, moduleIndex) => (
              <View key={moduleIndex} style={styles.moduleItem}>
                <Text style={styles.moduleName}>{module.name}</Text>
                <Text style={styles.moduleType}>{module.type}</Text>
                <Text style={styles.moduleEvcs}>{module.evcValue} EVCs</Text>
              </View>
            ))}
          </View>
        ))}
        
        {/* Resource allocation if available */}
        {resourceAllocation && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Resource Allocation</Text>
            <View style={styles.resourceBar}>
              {/* Use getColorFromCssVar to retrieve colors dynamically */}
              <View style={{ ...styles.resourceSegment, width: '60%', backgroundColor: elexivePrimary }} />
              <View style={{ ...styles.resourceSegment, width: '40%', backgroundColor: getColorFromCssVar('--elexive-accent', '#4F46E5') }} />
            </View>
          </View>
        )}
      </View>
      
      <View style={styles.footer}>
        <Text style={styles.coverFooterText}>
          CONFIDENTIAL: This report was generated by the Elexive Calculator for your organization.
        </Text>
        <Text style={styles.pageNumber}>Page 2 of 2</Text>
      </View>
    </Page>
  );
};

export default ReportContentPage;