// filepath: /Users/rolle/git/elexive-calc/src/pdf/components/ReportCoverPage.js
// Cover page component for PDF report generation

import React from 'react';
import { Page, Text, View } from '@react-pdf/renderer';
import styles from '../utils/pdfStyles';

/**
 * The cover page of the PDF report
 */
const ReportCoverPage = ({ 
  formattedDate, 
  intent, 
  totalPrice, 
  completionTimeWeeks, 
  totalEvcValue, 
  formatNumber 
}) => {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.headerBanner}>
        <Text style={styles.headerTitle}>Executive Solution Brief</Text>
      </View>
      
      <View style={styles.contentPage}>
        <Text style={styles.subTitle}>Strategic Transformation Plan</Text>
        <Text style={styles.dateText}>Generated on {formattedDate}</Text>
        
        {intent && (
          <View style={styles.intentContainer}>
            <Text style={styles.intentLabel}>BUSINESS OBJECTIVE</Text>
            <Text style={styles.intentText}>{intent}</Text>
          </View>
        )}
        
        <View style={styles.metricsRow}>
          <View style={styles.investmentMetric}>
            <Text style={styles.investmentLabel}>INVESTMENT</Text>
            <Text style={styles.investmentValue}>€{formatNumber(totalPrice)}</Text>
            <Text style={styles.investmentPeriod}>Weekly</Text>
          </View>
          
          <View style={styles.completionMetric}>
            <Text style={styles.completionLabel}>ESTIMATED COMPLETION</Text>
            <Text style={styles.completionValue}>{completionTimeWeeks} weeks</Text>
            <Text style={styles.completionTotal}>{totalEvcValue} EVCs total</Text>
          </View>
        </View>
        
        <View style={styles.logoPlaceholder}>
          <Text style={styles.logoText}>Elexive</Text>
        </View>
      </View>
      
      <View style={styles.footer}>
        <Text style={styles.coverFooterText}>
          CONFIDENTIAL: This report was generated by the Elexive Calculator for your organization.
        </Text>
        <Text style={styles.pageNumber}>Page 1 of 2</Text>
      </View>
    </Page>
  );
};

export default ReportCoverPage;